//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBins.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMember
    {
        public int ID { get; set; }
        public int IssueID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByID { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual User Member { get; set; }
        public virtual User CreatedBy { get; set; }
    }
}
