//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBins.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
