//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPlan.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.TeamMembers = new HashSet<TeamMember>();
            this.TeamMemberRequests = new HashSet<TeamMemberRequest>();
            this.Projects = new HashSet<Project>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        public virtual ICollection<TeamMemberRequest> TeamMemberRequests { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
