//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPlan.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
