//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBins.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotificationSubscription
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int NotificationTypeID { get; set; }
        public int TeamID { get; set; }
        public bool Subscribed { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
